name: bohurupi_order_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  fl_chart: ^0.66.2
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1
  font_awesome_flutter: ^10.7.0
  material_design_icons_flutter: ^7.0.7296
  iconsax: ^0.0.8
  intl: ^0.19.0
  http: ^1.2.0
  foundation: ^0.0.5
  url_launcher: ^6.2.5
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.4.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/app-icon.png

flutter_launcher_icons:
  android: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app-icon.png"
  image_path: "assets/images/app-icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/app-icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/images/app-icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/app-icon.png"
